stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3-openjdk-8
      shellScript: |
        mkdir target;
- name: Build Docker with DIND
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: celticmask/mod-pubsub:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
<<<<<<< HEAD
      registry: index.docker.io
=======
      registry: registry.hub.docker.com
>>>>>>> 5799a0a55b3d88febe2e1bc1c9da2ad1df192ff4
- name: Deploy
  steps:
  - applyAppConfig:
      catalogTemplate: p-mf42h:folijet-helmcharts-mod-pubsub
      version: 0.1.0
      answers:
        image.repository: celticmask/mod-pubsub
        image.tag: ${CICD_EXECUTION_SEQUENCE}
      name: mod-pub-sub
      targetNamespace: folijet
timeout: 60
notification: {}
