stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3-openjdk-8
      shellScript: mvn package -DskipTests
- name: Build Docker with DIND
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: mod-pubsub:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyAppConfig:
      catalogTemplate: p-mf42h:folijet-helmcharts-mod-pubsub
      version: 0.1.0
      name: mod-pubsub-dev1
      targetNamespace: folijet
timeout: 60
notification: {}
