stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3-openjdk-8
      shellScript: mvn package -DskipTests
- name: Build Docker with DIND
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: mod-pubsub:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 127.0.0.1:34524
- name: Deploy
  steps:
  - applyAppConfig:
      catalogTemplate: p-mf42h:folijet-helmcharts-mod-pubsub
      version: 0.1.0
      answers:
        image.repository: registry.ci.folio.org:5000/mod-pubsub
        image.tag: ${CICD_EXECUTION_SEQUENCE}
      name: mod-pubsub
      targetNamespace: folijet
timeout: 60
notification: {}
