stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3-openjdk-8
      shellScript: |
        mkdir target;
- name: Build Docker with DIND
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: celticmask/mod-pubsub:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: index.docker.io
- name: Deploy
  steps:
  - applyAppConfig:
      catalogTemplate: p-mf42h:folijet-helmcharts-mod-pubsub
      version: 0.1.0
      answers:
        image.repository: celticmask/mod-pubsub
        image.tag: ${CICD_EXECUTION_SEQUENCE}
      targetNamespace: folijet
timeout: 60
notification: {}
